# Generated by Django 3.2.15 on 2023-02-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0002_alter_addresscoordinate_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresscoordinate',
            old_name='request_date',
            new_name='requested_at',
        ),
    ]
