# Generated by Django 3.2.15 on 2023-01-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230102_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProductNew',
            new_name='OrderProduct',
        ),
    ]
