# Generated by Django 3.2.15 on 2023-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20230128_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('EL', 'Электронными'), ('CS', 'Наличными')], db_index=True, max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
