# Generated by Django 3.2.15 on 2023-01-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_copy_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='foodcartapp.OrderProductNew', to='foodcartapp.Product', verbose_name='Продукты'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
