# Generated by Django 3.2.15 on 2023-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230102_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('EL', 'Электронными'), ('CS', 'Наличными')], db_index=True, default='CS', max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
